// 2025-01-12-react-4/social-network-client/src/components/posts/post/Post.tsx
import './Post.css'
import PostModel from '../../../models/post/Post'
import profileService from '../../../services/profile'
import { useNavigate } from 'react-router-dom'
import Comments from '../postComments/comment/Comment'

interface PostProps {
    post: PostModel
    isAllowActions?: boolean
    remove?(id: string): void
}

export default function Post(props: PostProps): JSX.Element {
    const { title, body, createdAt, id } = props.post
    const { name } = props.post.user
    const navigate = useNavigate()

    async function deleteMe() {
        if (props.remove && confirm(`are you sure you want to delete "${title}"`))
            try {
                await profileService.remove(id)
                props.remove(id)
                // i was able to delete from the server
                // this is the point to affect the UI
                // in other words, we need to change the state
            } catch (e) {
                alert(e)
            }
    }

    function editMe() {
        navigate(`/edit/${id}`)
    }

    return (
        <div className='Post'>
            <div>
                {title}
            </div>
            <div>
                {name} at {createdAt}
            </div>
            <div>
                {body}
            </div>
            {props.isAllowActions &&
                <div>
                    <button onClick={editMe}>Edit</button>
                    <button onClick={deleteMe}>Delete</button>
                </div>
            }

            <Comments postId={id} />
        </div>
    )
}

// 2025-03-30-angular/02-social-network-client/src/app/components/posts/post/post.component.ts
import { Component, input, output, signal } from '@angular/core';
import { Post } from '../../../models/post/post.model';
import { ProfileService } from '../../../services/profile.service';
import { CommentsComponent } from "../comments/comments.component";
import { PostComment } from '../../../models/comment/comment.model';

@Component({
  selector: 'app-post',
  imports: [CommentsComponent],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

  constructor(
    public profileService: ProfileService
  ) { }
  post = input<Post>()
  comments = signal<PostComment[]>([])

  deletedPost = output<string>()

  async deleteMe() {
    try {
      await this.profileService.deletePost(this.post()!.id)
      this.deletedPost.emit(this.post()!.id)
    } catch (e) {
      alert(e)
    }
  }
}

<div id="post">
    <h3>{{post()?.title}}</h3>
    <p>by {{post()?.user?.name}} at {{post()?.createdAt}}</p>
    <div>{{post()?.body}}</div>
    <button (click)="deleteMe()">delete</button>
    <div>
        <app-comments [comments]="post()?.comments" [postId]="post()?.id">
        </app-comments>

    </div>
</div>
