// 2025-04-01-angular-crud/frontend/src/app/components/posts/post/post.component.ts
import { Component, input, output, signal } from '@angular/core';
import { ProfileService } from '../../../services/profile.service';
import { CommentsComponent } from "../comments/comments.component";
import { PostComment } from '../../../models/comment/comment.model';
import { Post } from '../../../models/post/draft.model';
import { Router } from '@angular/router';

@Component({
  selector: 'app-post',
  imports: [CommentsComponent],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {

  constructor(
    public profileService: ProfileService,
    public router: Router
  ) { }
  post = input<Post>()
  deletedPost = output<string>()
  deletedComment = output<{ postId: string, commentId: string }>()

  removeComment(id: string) {
    this.deletedComment.emit({ postId: this.post()!.id, commentId: id })
  }

  async editMe() {
    try {
      this.router.navigate([`/edit/${this.post()!.id}`])
    } catch (e) {
      alert(e)
    }
  }

  async deleteMe() {
    try {
      await this.profileService.deletePost(this.post()!.id)
      this.deletedPost.emit(this.post()!.id)
    } catch (e) {
      alert(e)
    }
  }
}

<div id="post">
    <h3>{{post()?.title}}</h3>
    <p>by {{post()?.user?.name}} at {{post()?.createdAt}}</p>
    <div>{{post()?.body}}</div>
    <button (click)="deleteMe()">delete</button>
    <button (click)="editMe()">edit me</button>
    <div>
        <app-comments [comments]="post()?.comments" [postId]="post()?.id" (deletedComment)="removeComment($event)">
        </app-comments>

    </div>
</div>

// 2025-01-12-react-5/social-network-client/src/components/posts/post/Post.tsx
import './Post.css'
import PostModel from '../../../models/post/Post'
import profileService from '../../../services/profile'
import { useNavigate } from 'react-router-dom'
import Comments from '../postComments/comments/Comments'
import LoadingButton from '../../common/loadingButton/LoadingButton'
import { useState } from 'react'
import { remove } from '../../../redux/profileSlice'
import { useAppDispatch } from '../../../redux/hooks'

interface PostProps {
    post: PostModel
    isAllowActions?: boolean
}

export default function Post(props: PostProps): JSX.Element {
    const { title, body, createdAt, id, comments } = props.post
    const { name } = props.post.user
    const navigate = useNavigate()
    const [isLoading, setIsLoading] = useState<boolean>(false)



    const dispatch = useAppDispatch()

    async function deleteMe() {
        if (confirm(`are you sure you want to delete "${title}"`))
            try {
                setIsLoading(true)
                await profileService.remove(id)
                dispatch(remove({ id }))
            } catch (e) {
                alert(e)
            } finally {
                setIsLoading(false)
            }
    }

    function editMe() {
        navigate(`/edit/${id}`)
    }

    return (
        <div className='Post'>
            <div>
                {title}
            </div>
            <div>
                {name} at {createdAt}
            </div>
            <div>
                {body}
            </div>
            {props.isAllowActions &&
                <div className='buttons'>
                    <button type="button" className="btn btn-secondary btn-sm" onClick={editMe}>Edit</button>
                    {isLoading ? <LoadingButton message={'deleting post'} /> :
                        <button type="button" className="btn btn-danger btn-sm" onClick={deleteMe}>Delete</button>}
                </div>
            }

            <Comments
                comments={comments}
                postId={id}
            />
        </div>
    )
}
